
/* Code automatically generated by Vult https://github.com/modlfo/vult */
#include "engine.h"

void Processor__ctx_type_0_init(Processor__ctx_type_0 &_output_){
   Processor__ctx_type_0 _ctx;
   _ctx.process_ret_3 = 0.0f;
   _ctx.process_ret_2 = 0.0f;
   _ctx.process_ret_1 = 0.0f;
   _ctx.process_ret_0 = 0.0f;
   _ctx.param4 = 0.0f;
   _ctx.param3 = 0.0f;
   _ctx.param2 = 0.0f;
   _ctx.param1 = 0.0f;
   _output_ = _ctx;
   return ;
}

void Processor_process(Processor__ctx_type_0 &_ctx, float in1, float in2, float in3, float in4){
   float out1;
   float out2;
   float out3;
   float out4;
   out1 = in1;
   out2 = in2;
   out3 = in3;
   out4 = in4;
   out1 = ((_ctx.param1 * in1) + (in2 * (1.f + (- _ctx.param1))));
   _ctx.process_ret_0 = out1;
   _ctx.process_ret_1 = out2;
   _ctx.process_ret_2 = out3;
   _ctx.process_ret_3 = out4;
   return ;
}


